### ISSUE TITLE
Figma de tela de auditoria

### ISSUE THREAD

**Issue by robertdiniz** [IF-Community/if-community-frontend#13]
Criação das telas de auditoria, Login, CRUD e Requisição

**Comment by kennedywc** [comment]
@robertdiniz @WillianM19 

Crie as telas, mas olhem aí se é isso mesmo [LINK AQUI!](https://www.figma.com/design/t3HCSN036G1FYvjO8r5Got/Design?node-id=0-1&t=l021RZZkb8pV8pZf-1)
