### ISSUE TITLE
Figma da tela de cadastro

### ISSUE THREAD

**Issue by kennedywc** [IF-Community/if-community-frontend#44]

**Comment by kennedywc** [comment]
@robertdiniz @WillianM19

Por favor, verifiquem as telas e confiram se estão conforme o esperado.

O link para acesso está disponível aqui!

**Comment by WillianM19** [comment]
### Figma atual:

![Image](https://github.com/user-attachments/assets/31e0fb54-b0a3-452c-afa9-eec3f10a65d2)

- Acho que poderia ajustar a barra de navegação para seguir o layout das outras páginas
- Ajustar a parte da seleção de imagem, que saiu um pouco do padrão visual
- Adicionar um título seria bacana também
- Talvez rever a cor das bordas e fundo dos inputs
