### ISSUE TITLE
FIgma da tela de cadastrar post

### ISSUE THREAD

**Issue by kennedywc** [IF-Community/if-community-frontend#46]

**Comment by kennedywc** [comment]
@robertdiniz @WillianM19

Por favor, verifiquem as telas e confiram se estão conforme o esperado.

O link para acesso está disponível aqui!

**Comment by WillianM19** [comment]
### Figma atual:

![Image](https://github.com/user-attachments/assets/5ba1507a-fa69-4444-918f-d1be43068da7)

- Ajustar o padding do container
- Talvez adicionar labels pros inputs
- Um título talvez seria bacana nesta página
